package com.smalltalknow.service.controller.websocket;

public class EntityConstant {
    public static final String FILE_INFO_FILE_ID = "file_id";
    public static final String FILE_INFO_FIRST_SELECTOR = "first_selector";
    public static final String FILE_INFO_SECOND_SELECTOR = "second_selector";
    public static final String FILE_INFO_FILE_NAME = "file_name";
    public static final String FILE_INFO_FILE_LINK = "file_link";
    public static final String FILE_INFO_FILE_UPLOADER = "file_uploader";
    public static final String FILE_INFO_FILE_UPLOAD_TIME = "file_upload_time";
    public static final String FILE_INFO_FILE_EXPIRE_TIME = "file_expire_time";
    public static final String FILE_INFO_FILE_SIZE = "file_size";
    public static final String FILE_INFO_FILE_DOWNLOADS = "file_downloads";
    public static final String GROUP_INFO_GROUP_ID = "group_id";
    public static final String GROUP_INFO_GROUP_HOST_ID = "group_host_id";
    public static final String GROUP_INFO_GROUP_NAME = "group_name";
    public static final String GROUP_INFO_GROUP_INFO = "group_info";
    public static final String GROUP_INFO_GROUP_AVATAR_LINK = "group_avatar_link";
    public static final String GROUP_INFO_MEMBER_LIST = "member_list";
    public static final String REQUEST_INFO_REQUEST_ID = "request_id";
    public static final String REQUEST_INFO_REQUEST_STATUS = "request_status";
    public static final String REQUEST_INFO_REQUEST_TYPE = "request_type";
    public static final String REQUEST_INFO_REQUEST_METADATA = "request_metadata";
    public static final String USER_INFO_USER_ID = "user_id";
    public static final String USER_INFO_USER_SESSION = "user_session";
    public static final String USER_INFO_USER_EMAIL = "user_email";
    public static final String USER_INFO_USER_NAME = "user_name";
    public static final String USER_INFO_USER_PASSWORD = "user_password";
    public static final String USER_INFO_USER_GENDER = "user_gender";
    public static final String USER_INFO_USER_AVATAR_LINK = "user_avatar_link";
    public static final String USER_INFO_USER_INFO = "user_info";
    public static final String USER_INFO_USER_LOCATION = "user_location";
    public static final String USER_INFO_USER_CONTACT_LIST = "user_contact_list";
    public static final String USER_INFO_USER_GROUP_LIST = "user_group_list";
    public static final String USER_INFO_USER_REQUEST_LIST = "user_request_list";
    public static final String CONTACT_INFO_CONTACT_ID = "contact_id";
    public static final String CONTACT_INFO_CONTACT_EMAIL = "contact_email";
    public static final String CONTACT_INFO_CONTACT_NAME = "contact_name";
    public static final String CONTACT_INFO_CONTACT_GENDER = "contact_gender";
    public static final String CONTACT_INFO_CONTACT_AVATAR_LINK = "contact_avatar_link";
    public static final String CONTACT_INFO_CONTACT_INFO = "contact_info";
    public static final String CONTACT_INFO_CONTACT_LOCATION = "contact_location";
}
